# -*- coding: utf-8 -*-

"""
feedbackapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from feedbackapi.api_helper import APIHelper


class CredentialsControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(CredentialsControllerTests, cls).setUpClass()
        cls.controller = cls.client.credentials
        cls.response_catcher = cls.controller.http_call_back

    # ### Start here by creating your credentials
    #Be careful to save the private key that is returned. You will not be able to retrieve it again.
    #You can only have one private key at a time.
    #Private key is not to be shared with anyone, do not expose it in your frontend code.
    #
    def test_create_credentials(self):

        # Perform the API call through the SDK function
        result = self.controller.create_credentials()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


