# -*- coding: utf-8 -*-

"""
feedbackapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from feedbackapi.api_helper import APIHelper


class Data(object):

    """Implementation of the 'Data' model.

    TODO: type model description here.

    Attributes:
        code (string): TODO: type description here.
        expected (string): TODO: type description here.
        received (string): TODO: type description here.
        path (list of string): TODO: type description here.
        message (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": 'code',
        "expected": 'expected',
        "received": 'received',
        "path": 'path',
        "message": 'message'
    }

    _optionals = [
        'code',
        'expected',
        'received',
        'path',
        'message',
    ]

    def __init__(self,
                 code=APIHelper.SKIP,
                 expected=APIHelper.SKIP,
                 received=APIHelper.SKIP,
                 path=APIHelper.SKIP,
                 message=APIHelper.SKIP):
        """Constructor for the Data class"""

        # Initialize members of the class
        if code is not APIHelper.SKIP:
            self.code = code 
        if expected is not APIHelper.SKIP:
            self.expected = expected 
        if received is not APIHelper.SKIP:
            self.received = received 
        if path is not APIHelper.SKIP:
            self.path = path 
        if message is not APIHelper.SKIP:
            self.message = message 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        code = dictionary.get("code") if dictionary.get("code") else APIHelper.SKIP
        expected = dictionary.get("expected") if dictionary.get("expected") else APIHelper.SKIP
        received = dictionary.get("received") if dictionary.get("received") else APIHelper.SKIP
        path = dictionary.get("path") if dictionary.get("path") else APIHelper.SKIP
        message = dictionary.get("message") if dictionary.get("message") else APIHelper.SKIP
        # Return an object of this model
        return cls(code,
                   expected,
                   received,
                   path,
                   message)
