# -*- coding: utf-8 -*-

"""
feedbackapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from feedbackapi.api_helper import APIHelper


class Pagination(object):

    """Implementation of the 'Pagination' model.

    Pagination object.

    Attributes:
        page (int): Current page.
        per_page (int): Number of items per page.
        total (int): Total number of items.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "page": 'page',
        "per_page": 'perPage',
        "total": 'total'
    }

    _optionals = [
        'page',
        'per_page',
        'total',
    ]

    def __init__(self,
                 page=APIHelper.SKIP,
                 per_page=APIHelper.SKIP,
                 total=APIHelper.SKIP):
        """Constructor for the Pagination class"""

        # Initialize members of the class
        if page is not APIHelper.SKIP:
            self.page = page 
        if per_page is not APIHelper.SKIP:
            self.per_page = per_page 
        if total is not APIHelper.SKIP:
            self.total = total 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        page = dictionary.get("page") if dictionary.get("page") else APIHelper.SKIP
        per_page = dictionary.get("perPage") if dictionary.get("perPage") else APIHelper.SKIP
        total = dictionary.get("total") if dictionary.get("total") else APIHelper.SKIP
        # Return an object of this model
        return cls(page,
                   per_page,
                   total)
