# -*- coding: utf-8 -*-

"""
feedbackapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class XORDEREnum(object):

    """Implementation of the 'X-ORDER' enum.

    TODO: type enum description here.

    Attributes:
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """

    ASC = 'asc'

    DESC = 'desc'
