# -*- coding: utf-8 -*-

"""
feedbackapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class XORDERBYEnum(object):

    """Implementation of the 'X-ORDER-BY' enum.

    TODO: type enum description here.

    Attributes:
        RATING: TODO: type description here.
        CREATEDAT: TODO: type description here.

    """

    RATING = 'rating'

    CREATEDAT = 'createdAt'
